name: phage_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12.12
  - pip=26.0.1
  - aragorn=1.2.41
  - dnaapler=1.3.0
  - mash=2.3
  - minced=0.4.2
  - mmseqs2=18.8cc5c
  - pharokka=1.9.1
  - trnascan-se=2.0.12
  - pip:
      - -r requirements.txt
